### ISSUE TITLE
ServiceLocator vs DI

### ISSUE THREAD

**Issue by PaNaVTEC** [Karumi/BothamUI#21]
Hi guys,

Can I ask you why you recommend using a Service Locator pattern instead of a DI framework like Typhoon?

Many thanks!

pd. Flag this as a question, I can't do it.

**Comment by davideme** [comment]
The problem of Typhoon is that everything should be an NSObject, and we don't want to force users of our framework to define everything as NSObject.

We could use https://github.com/Swinject/Swinject but, we prefer for the first version, to not be tight a lib. But we continue to investigate and take a look to https://github.com/briancroom/BlindsidedStoryboard

**Comment by PaNaVTEC** [comment]
Hi davideme, thanks for your answer! 
I'm not saying to include Typhoon or Swinject in your framework. It is only to suggest the use of a DI instead of a service locator pattern which is considered as an antipattern around the internet, I think the final users are who need to decice what are their needs. But it is only a suggestion, I sometimes use this pattern for my examples :+1: 
Thanks again for your time and keep the good work!

**Comment by davideme** [comment]
If you take a look at the example, we are using the di pattern all over the
code. But instead of using di framework we use a service locator or a di
container it depend how you want to call it. To initialize the
viewcontrollers and dependencies.

Basically we use DI, without a framework.
