### ISSUE TITLE
The name BothamDataSource can be problematic in the future, should we change the prefix ? 

### ISSUE THREAD

**Issue by davideme** [Karumi/BothamUI#24]
If in another Botham project we introduce backend DataSource how should we resolved this ?

**Comment by pedrovgs** [comment]
We can change it to `BothamTableViewDataSource` if you want or just `BothamViewDataSource`. What do you think?

**Comment by davideme** [comment]
BothamViewDataSource is fine

**Comment by davideme** [comment]
:+1:

**Comment by davideme** [comment]
fixed in #26
